DROP DATABASE IF EXISTS login;
CREATE DATABASE IF NOT EXISTS login
DEFAULT CHARSET = utf8
DEFAULT COLLATE = utf8_general_ci;

USE login;

DROP TABLE IF EXISTS tb_users;
CREATE TABLE IF NOT EXISTS tb_users (
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    pwd VARCHAR(32) NOT NULL UNIQUE,
    CONSTRAINT PK_users PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
